### ISSUE TITLE
Support for rational numbers

### ISSUE THREAD

**Issue by 0joshuaolson1** [tiehuis/zig-bn#12]
That is, ignoring division/modulus, also tracking a binary exponent `2^n` (with fixed `n < 0` if fixed-point?) to make a kind of rational number.

I can just wrap this library with exponent tracking for my use case, which doesn't need bit shifting.

**Comment by tiehuis** [comment]
I'm in the process of writing a Rational number wrapper now, since this is useful for the self-hosted compiler. A general purpose arbitrary precision floating point I won't be implementing any time soon, however.

**Comment by 0joshuaolson1** [comment]
Rational is a superset of floating point (ignoring hardware primitives), so I look forward to that.

**Comment by tiehuis** [comment]
Current implementation should be usable right now so closing. Let me know if there are any other specific functions that may be useful or I have missed.

Will merge into zig std sometime soon as well.
