### ISSUE TITLE
Initial Function Implementation

### ISSUE THREAD

**Issue by tiehuis** [tiehuis/zig-bn#6]
Checklist for core functions to implement. There are more functions I would like to cover, namely achieving rough parity with GMP, but the following are a good start.

 - [x] mul
 - [x] add
 - [x] sub
 - [x] neg
 - [x] abs
 - [x] divMod (floor/mod)
 - [x] divRem (trunc/rem)
 - [x] cmp
 - [x] sign
 - [x] left shift
 - [x] right shift
 - [x] xor
 - [x] ior
 - [x] and
 - [x] set (integer)
 - [x] set (string)
 - [x] to (integer)
 - [x] to (string)

**Comment by andrewrk** [comment]
It would be nice to have [divTrunc](http://ziglang.org/documentation/#builtin-divTrunc), [divFloor](http://ziglang.org/documentation/#builtin-divFloor), [mod](http://ziglang.org/documentation/#builtin-mod), and [rem](http://ziglang.org/documentation/#builtin-rem)

**Comment by tiehuis** [comment]
Done besides some behaviour details and sign checks.
